export const TOGGLE_LIGHT_AUTOMATIC_MOVEMENT = "TOGGLE_LIGHT_AUTOMATIC_MOVEMENT";
export const TOGGLE_LIGHT_ORIGIN = "TOGGLE_LIGHT_ORIGIN";
export const UPDATE_LIGHT_COORD = "UPDATE_LIGHT_COORD";
export const UPDATE_LIGHT_REACH = "UPDATE_LIGHT_REACH";
export const UPDATE_LIGHT_X_INCREMENT = "UPDATE_LIGHT_X_INCREMENT";
export const UPDATE_LIGHT_Y_INCREMENT = "UPDATE_LIGHT_Y_INCREMENT";
export const UPDATE_LIGHT_START = "UPDATE_LIGHT_START";